import fs from "node:fs";
import vm from "node:vm";

const BUS_FILE = "data/cuhk_bus_routes.js";
const ROADS_FILE = "data/cuhk_roads_poi_coffee_tea_clipped.geojson";
const DRIVEABLE_HIGHWAYS = new Set([
  "motorway",
  "trunk",
  "primary",
  "secondary",
  "tertiary",
  "unclassified",
  "residential",
  "service",
]);

const STOP_OVERRIDES = {
  university_station: { coord: [114.2102205, 22.4145368], osmId: "node/1716519472" },
  university_station_piazza: { coord: [114.2094368, 22.4138075], osmId: "node/2036051433" },
  yasumoto: { coord: [114.2108317, 22.4159729], osmId: "node/2035049978" },
  chung_chi_teaching: { coord: [114.208359, 22.4160358], osmId: "node/1716519526" },
  university_sports_centre: { coord: [114.2104816, 22.4178117], osmId: "node/1716519481" },
  shaw_hall: { coord: [114.2069424, 22.419841], osmId: "node/1716519535" },
  science_centre: { coord: [114.2073418, 22.4198305], osmId: "node/2035104642" },
  fung_king_hey: { coord: [114.2030318, 22.4198637], osmId: "node/1716519434" },
  university_admin: { coord: [114.2053581, 22.418806], osmId: "node/1716519519" },
  sh_ho: { coord: [114.2098498, 22.4180416], osmId: "node/2035104643" },
  united_college: { coord: [114.2053167, 22.4202884], osmId: "node/1716519514" },
  new_asia: { coord: [114.2076174, 22.4210995], osmId: "node/2036051434" },
  residences_3_4: { name: "伍宜孙书院 / 三、四苑", coord: [114.2034714, 22.4213306], osmId: "node/2035104644" },
  shaw_college: { coord: [114.2013149, 22.4224859], osmId: "node/1716519477" },
  postgraduate_hostel: { coord: [114.2121715, 22.4202482], osmId: "node/1716519492" },
  cw_chu: { coord: [114.2062179, 22.4255566], osmId: "node/2035133243" },
  area_39: { coord: [114.2043508, 22.427631], osmId: "node/2035114211" },
  residence_15: { coord: [114.2065975, 22.4237161], osmId: "node/2035133252" },
  united_residence: { coord: [114.2051303, 22.4232591], osmId: "node/2035204920" },
  residence_10_11: { coord: [114.208289, 22.4245673], osmId: "node/2035133259" },
  chan_chun_ha_hostel: { coord: [114.204626, 22.4218434], osmId: "node/2035204924" },
  campus_circuit_east: { coord: [114.2129002, 22.4192822], osmId: "node/5265944663" },
};

const context = { Intl, Date, console };
vm.runInNewContext(fs.readFileSync(BUS_FILE, "utf8"), context);
const data = context.CUHK_BUS_DATA;
const roadData = JSON.parse(fs.readFileSync(ROADS_FILE, "utf8"));

for (const [id, override] of Object.entries(STOP_OVERRIDES)) {
  if (!data.stops[id]) throw new Error(`Unknown stop override: ${id}`);
  Object.assign(data.stops[id], override);
}

data.metadata.source = "CUHK Transport Office route listings/PDFs, OpenStreetMap bus-stop nodes, and local OpenStreetMap campus road centerlines.";
data.metadata.coordinateNote = "Stops with osmId use OpenStreetMap bus-stop/platform nodes; remaining paid-shuttle intermediate stops use nearest reviewed map anchors.";
data.metadata.pathNote = "All route paths are generated by snapping stop sequences to the local OpenStreetMap driveable campus road network. Route 1A remains based on the reviewed OSM road-centerline path.";

const network = buildRoadNetwork(roadData);
const report = [];
for (const route of data.routes) {
  if (route.id === "1A") {
    route.pathSource = "reviewed_osm_road_centerline";
    continue;
  }
  const result = buildRoutePath(route, data.stops, network);
  route.path = result.path;
  route.pathSource = "generated_osm_road_network";
  report.push({
    route: route.id,
    points: result.path.length,
    maxSnapMeters: Math.round(result.maxSnapMeters),
    fallbackLegs: result.fallbackLegs,
  });
}

writeBusFile(data);
console.table(report);

function buildRoadNetwork(collection) {
  const segments = [];
  const graph = new Map();
  for (const feature of collection.features) {
    const props = feature.properties || {};
    const geom = feature.geometry || {};
    if (!DRIVEABLE_HIGHWAYS.has(props.highway) || geom.type !== "LineString") continue;
    const coords = geom.coordinates.map(roundCoord);
    for (let i = 1; i < coords.length; i += 1) {
      const a = coords[i - 1];
      const b = coords[i];
      if (sameCoord(a, b)) continue;
      const length = distanceMeters(a, b);
      segments.push({ a, b, length });
      addGraphEdge(graph, key(a), key(b), length);
      addGraphEdge(graph, key(b), key(a), length);
    }
  }
  return { graph, segments };
}

function buildRoutePath(route, stops, network) {
  const graph = cloneGraph(network.graph);
  const virtuals = new Map();
  let maxSnapMeters = 0;

  for (const stopId of [...new Set(route.stops)]) {
    const stop = stops[stopId];
    if (!stop) throw new Error(`Route ${route.id} references unknown stop ${stopId}`);
    const snap = nearestRoadPoint(stop.coord, network.segments);
    maxSnapMeters = Math.max(maxSnapMeters, snap.distance);
    const virtualKey = `stop:${stopId}`;
    virtuals.set(stopId, { key: virtualKey, coord: snap.coord, distance: snap.distance });
    addGraphEdge(graph, virtualKey, key(snap.segment.a), distanceMeters(snap.coord, snap.segment.a));
    addGraphEdge(graph, key(snap.segment.a), virtualKey, distanceMeters(snap.coord, snap.segment.a));
    addGraphEdge(graph, virtualKey, key(snap.segment.b), distanceMeters(snap.coord, snap.segment.b));
    addGraphEdge(graph, key(snap.segment.b), virtualKey, distanceMeters(snap.coord, snap.segment.b));
  }

  const path = [];
  const fallbackLegs = [];
  for (let i = 1; i < route.stops.length; i += 1) {
    const fromId = route.stops[i - 1];
    const toId = route.stops[i];
    const from = virtuals.get(fromId);
    const to = virtuals.get(toId);
    const legKeys = dijkstra(graph, from.key, to.key);
    let coords;
    if (legKeys.length) {
      coords = legKeys.map((item) => virtualsByKey(virtuals).get(item)?.coord || coordFromKey(item));
    } else {
      coords = [from.coord, to.coord];
      fallbackLegs.push(`${fromId}->${toId}`);
    }
    appendCoords(path, coords);
  }

  return {
    path: simplifyPath(path).map(roundCoord),
    maxSnapMeters,
    fallbackLegs,
  };
}

function cloneGraph(graph) {
  return new Map([...graph.entries()].map(([node, edges]) => [node, edges.map((edge) => ({ ...edge }))]));
}

function addGraphEdge(graph, from, to, weight) {
  if (!graph.has(from)) graph.set(from, []);
  graph.get(from).push({ to, weight });
}

function dijkstra(graph, start, target) {
  const dist = new Map([[start, 0]]);
  const prev = new Map();
  const queue = new Set(graph.keys());
  queue.add(start);
  queue.add(target);

  while (queue.size) {
    let current = null;
    let currentDist = Infinity;
    for (const node of queue) {
      const value = dist.get(node) ?? Infinity;
      if (value < currentDist) {
        current = node;
        currentDist = value;
      }
    }
    if (current === null || currentDist === Infinity) break;
    queue.delete(current);
    if (current === target) break;
    for (const edge of graph.get(current) || []) {
      const nextDist = currentDist + edge.weight;
      if (nextDist < (dist.get(edge.to) ?? Infinity)) {
        dist.set(edge.to, nextDist);
        prev.set(edge.to, current);
        queue.add(edge.to);
      }
    }
  }

  if (!dist.has(target)) return [];
  const path = [];
  for (let node = target; node; node = prev.get(node)) {
    path.push(node);
    if (node === start) break;
  }
  return path.reverse();
}

function nearestRoadPoint(coord, segments) {
  let best = null;
  for (const segment of segments) {
    const projected = projectPointToSegment(coord, segment.a, segment.b);
    const distance = distanceMeters(coord, projected);
    if (!best || distance < best.distance) {
      best = { coord: projected, distance, segment };
    }
  }
  if (!best) throw new Error("No road segments found");
  return best;
}

function projectPointToSegment(point, a, b) {
  const p = projectMeters(point);
  const pa = projectMeters(a);
  const pb = projectMeters(b);
  const dx = pb.x - pa.x;
  const dy = pb.y - pa.y;
  const lengthSquared = dx * dx + dy * dy;
  const t = lengthSquared ? Math.max(0, Math.min(1, ((p.x - pa.x) * dx + (p.y - pa.y) * dy) / lengthSquared)) : 0;
  return roundCoord([a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t]);
}

function projectMeters(coord) {
  const lat0 = 22.42 * Math.PI / 180;
  return {
    x: coord[0] * 111320 * Math.cos(lat0),
    y: coord[1] * 110540,
  };
}

function appendCoords(target, coords) {
  coords.forEach((coord) => {
    if (!target.length || !sameCoord(target[target.length - 1], coord)) {
      target.push(coord);
    }
  });
}

function simplifyPath(coords) {
  if (coords.length <= 2) return coords;
  const result = [coords[0]];
  for (let i = 1; i < coords.length - 1; i += 1) {
    const a = result[result.length - 1];
    const b = coords[i];
    const c = coords[i + 1];
    if (sameCoord(a, b) || isNearlyCollinear(a, b, c)) continue;
    result.push(b);
  }
  result.push(coords[coords.length - 1]);
  return result;
}

function isNearlyCollinear(a, b, c) {
  const pa = projectMeters(a);
  const pb = projectMeters(b);
  const pc = projectMeters(c);
  const area = Math.abs((pb.x - pa.x) * (pc.y - pa.y) - (pb.y - pa.y) * (pc.x - pa.x));
  const base = Math.hypot(pc.x - pa.x, pc.y - pa.y);
  return base > 0 && area / base < 0.15;
}

function virtualsByKey(virtuals) {
  return new Map([...virtuals.values()].map((item) => [item.key, item]));
}

function coordFromKey(value) {
  return value.split(",").map(Number);
}

function key(coord) {
  return `${coord[0].toFixed(7)},${coord[1].toFixed(7)}`;
}

function sameCoord(a, b) {
  return key(a) === key(b);
}

function roundCoord(coord) {
  return [Number(coord[0].toFixed(7)), Number(coord[1].toFixed(7))];
}

function distanceMeters(a, b) {
  const radius = 6371000;
  const lat1 = toRad(a[1]);
  const lat2 = toRad(b[1]);
  const dLat = toRad(b[1] - a[1]);
  const dLon = toRad(b[0] - a[0]);
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon / 2) ** 2;
  return 2 * radius * Math.atan2(Math.sqrt(h), Math.sqrt(1 - h));
}

function toRad(value) {
  return value * Math.PI / 180;
}

function writeBusFile(nextData) {
  const current = fs.readFileSync(BUS_FILE, "utf8");
  const marker = ";\n\nconst HK_TIME_ZONE";
  const markerIndex = current.indexOf(marker);
  if (markerIndex === -1) throw new Error("Could not find bus data/function boundary");
  const suffix = current.slice(markerIndex);
  const serialized = compactJson(JSON.stringify(nextData, null, 2));
  fs.writeFileSync(BUS_FILE, `(function (root) {\nroot.CUHK_BUS_DATA = ${serialized}${suffix}`);
}

function compactJson(value) {
  return value.replace(/\[\n\s+(-?\d+(?:\.\d+)?),\n\s+(-?\d+(?:\.\d+)?)\n\s+\]/g, "[$1, $2]");
}
